// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7KozjT8XBg5t3QLl8L3GpET4Acf-3ajs',
    appId: '1:280845664357:web:9871c589019d0a5e01868c',
    messagingSenderId: '280845664357',
    projectId: 'freelance-app-78e07',
    authDomain: 'freelance-app-78e07.firebaseapp.com',
    storageBucket: 'freelance-app-78e07.firebasestorage.app',
    measurementId: 'G-3XLGP10JYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm6xyFUVF0GfRYcMLPmOpucuDTn-wGs28',
    appId: '1:280845664357:android:535af8761b3c63bf01868c',
    messagingSenderId: '280845664357',
    projectId: 'freelance-app-78e07',
    storageBucket: 'freelance-app-78e07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS0sYlw-zvsrIFdGOidDfLDdBvp5sfox8',
    appId: '1:280845664357:ios:2b3b6900107b75d701868c',
    messagingSenderId: '280845664357',
    projectId: 'freelance-app-78e07',
    storageBucket: 'freelance-app-78e07.firebasestorage.app',
    androidClientId: '280845664357-186krkbslj5plfah1rbru5do7r61ut43.apps.googleusercontent.com',
    iosClientId: '280845664357-2f0ivfakt3emtfm8kpbq346ktaa10l3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelancingPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS0sYlw-zvsrIFdGOidDfLDdBvp5sfox8',
    appId: '1:280845664357:ios:2b3b6900107b75d701868c',
    messagingSenderId: '280845664357',
    projectId: 'freelance-app-78e07',
    storageBucket: 'freelance-app-78e07.firebasestorage.app',
    androidClientId: '280845664357-186krkbslj5plfah1rbru5do7r61ut43.apps.googleusercontent.com',
    iosClientId: '280845664357-2f0ivfakt3emtfm8kpbq346ktaa10l3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.freelancingPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7KozjT8XBg5t3QLl8L3GpET4Acf-3ajs',
    appId: '1:280845664357:web:f0a9e8b23646767501868c',
    messagingSenderId: '280845664357',
    projectId: 'freelance-app-78e07',
    authDomain: 'freelance-app-78e07.firebaseapp.com',
    storageBucket: 'freelance-app-78e07.firebasestorage.app',
    measurementId: 'G-VVTYS5DR57',
  );
}
